GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "sample",
    "important" : true
}

###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "test",
  "author": "test author",
  "url": "http://coolios.com",
  "likes": "234",
  "userId": "67bd338337cf5a8bd9be950a"
}

### 
PUT http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "test",
  "author": "test author",
  "url": "http://coolios.com",
  "likes": "234"
}

### 
POST http://localhost:3001/api/users 
content-type: application/json

{
   "username": "mduser",
    "name": "mduser",
    "password": "salainen"
}

###
post https://localhost:3001/api/login HTTP/1.1
content-type: application/json
{
  "username": "mduser",
  "password": "salainen"
}